# Generated by Django 5.0.6 on 2024-06-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('course', models.CharField(choices=[('BIT', 'BIT'), ('BBIT', 'BBIT'), ('BCOM', 'BCOM'), ('BED', 'BED')], max_length=20)),
            ],
        ),
    ]
